// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DoodlePop",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "DoodlePop",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.doodlepop",
            teamIdentifier: "",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .palette),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .photoLibrary(purposeString: "DoodlePop uses your photos so kids can turn them into coloring pages."),
                .camera(purposeString: "DoodlePop can take a photo and turn it into a coloring page.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
